// Builds assets/icons.js from Tabler Icons (MIT) + a few custom glyphs drawn for DRONEFALL.
// usage: node tools/build_icons.mjs <path-to-@tabler/icons/icons/outline> <out.js>
import fs from 'node:fs';
import path from 'node:path';

const [, , dir, out] = process.argv;
const TABLER = [
  'drone', 'drone-off', 'target', 'focus-2', 'crosshair', 'bomb', 'flame', 'hand-grab', 'repeat',
  'building-factory', 'building-factory-2', 'anchor', 'pick', 'train', 'building-castle', 'crown',
  'eye', 'scan-eye', 'radar', 'radar-2', 'antenna', 'book', 'masks-theater', 'plant', 'home',
  'building-bank', 'wall', 'shield', 'first-aid-kit', 'flare', 'network', 'affiliate', 'brain',
  'flask', 'headset', 'star', 'droplet', 'cloud-rain', 'volume', 'speakerphone', 'door', 'ghost',
  'bolt', 'chevrons-right', 'chevrons-down', 'tank', 'robot', 'robot-off', 'cpu', 'topology-star-3',
  'package', 'parachute', 'arrow-big-down-lines', 'infinity', 'skull', 'alert-triangle', 'radioactive',
  'lamp', 'candle', 'tower', 'building-broadcast-tower', 'satellite', 'map-pin', 'world', 'military-rank',
  'military-award', 'ripple', 'hexagon', 'circle-dashed', 'atom', 'steering-wheel', 'telescope', 'microphone',
];
const icons = {};
for (const n of TABLER) {
  const svg = fs.readFileSync(path.join(dir, `${n}.svg`), 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '')
    .replace(/<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*\/>/, '').replace(/\s+/g, ' ').trim();
  icons[n] = inner;
}
// custom glyphs (24x24, stroke based – same language as Tabler)
Object.assign(icons, {
  'gun-light': '<path d="M2.5 7.5h16v3.5h-6.5l-1 2h-2.5l-1.5 5h-3.5l1.6-5H2.5z"/><path d="M18.5 8.5h2.5"/><path d="M5 9.2h9"/>',
  'gun-mid': '<path d="M1.5 10h3l.8-1.5h11.2l.5 1h5.5v2h-5l-.8 1h-3.2l-1 4h-2.7l.9-4H8.5L7 14.5H4l.8-2.5H1.5z"/><path d="M9 8.5V7h4v1.5"/>',
  'gun-heavy': '<rect x="2" y="8.5" width="16" height="5" rx="1"/><path d="M18 9.5h3.5v3H18"/><path d="M6.5 13.5L5.5 18h3l1-4.5"/><path d="M11 8.5V6.5h4v2"/><path d="M4.5 11h11"/>',
  'throw': '<path d="M3 19c2.5-8 8-12 14-11.5" stroke-dasharray="1.5 2.5"/><circle cx="18.5" cy="8.5" r="3"/><path d="M18.5 5.5V3.8h2"/>',
  'burst': '<path d="M12 2l2.1 5.6 5.5-2.7-2.6 5.6L22 12l-5 1.6 2.6 5.5-5.5-2.6L12 22l-2.1-5.5-5.5 2.6 2.6-5.5L2 12l5-1.5-2.6-5.6 5.5 2.7z"/>',
  'leviathan': '<circle cx="12" cy="12" r="9"/><path d="M12 3.5l2.2 7.2h-4.4z"/><path d="M4.6 16.3l6.1-4.6.9 4.4z"/><path d="M19.4 16.3l-6.1-4.6-.9 4.4z"/><circle cx="12" cy="12.6" r="1.2"/>',
  'gate': '<circle cx="12" cy="12" r="9.5" stroke-dasharray="2.5 2"/><circle cx="12" cy="12" r="6.5"/><circle cx="12" cy="12" r="3"/>',
  'drop-drone': '<path d="M7 4.5h10"/><path d="M5 3v3"/><path d="M19 3v3"/><rect x="9" y="5.5" width="6" height="3" rx="1"/><path d="M12 8.5v4"/><path d="M8.5 15.5l3.5 3.5 3.5-3.5"/><path d="M8.5 11.5l3.5 3.5 3.5-3.5"/>',
});
fs.writeFileSync(out, `// generated by tools/build_icons.mjs — Tabler Icons (MIT) + custom glyphs\nwindow.ICONS = ${JSON.stringify(icons, null, 0)};\n`);
console.log('icons:', Object.keys(icons).length);
